{"errorMessage": "(psycopg2.errors.ObjectInUse) database \"bdsql\" is being accessed by other users\nDETAIL:  There are 2 other sessions using the database.\n\n[SQL: DROP DATABASE IF EXISTS bdsql]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", "errorType": "OperationalError", "requestId": "2587a10b-1a6b-4f14-bcf3-0da99c883712", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 14, in lambda_handler\n    session = create_database()\n", "  File \"/var/task/db.py\", line 34, in create_database\n    root_session.execute(text(f\"DROP DATABASE IF EXISTS {DB_NAME}\"))\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2362, in execute\n    return self._execute_internal(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2256, in _execute_internal\n    result = conn.execute(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1418, in execute\n    return meth(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/sql/elements.py\", line 515, in _execute_on_connection\n    return connection._execute_clauseelement(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1640, in _execute_clauseelement\n    ret = self._execute_context(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1846, in _execute_context\n    return self._exec_single_context(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1986, in _exec_single_context\n    self._handle_dbapi_exception(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 2355, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n", "  File \"/var/lang/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n    cursor.execute(statement, parameters)\n"]}